version: '3'
services:
  ppong-backend:
    build: ./backend/.
    ports:
      - 8080
    environment:
      - DEBUG=False
      - DB_HOST=ppong-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ppong
      - DB_SCHEMA=public
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@ppong-db/ppong
  ppong-frontend:
    build: ./frontend/.
    ports:
      - 80:80
  ppong-db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ppong
    ports:
      - 5433:5432
